services:
  temar_db:
    image: postgres:16-alpine
    container_name: prod_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pg_data_prod:/var/lib/postgresql/data
    networks:
      - temar_net

  migrate:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/migrate:latest
    container_name: prod_migrate
    restart: "no"
    env_file:
      - .env
    depends_on:
      - db
    command: ["pnpm", "run", "migrate:prod"]
  web:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/web:latest
    container_name: prod_web
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - migrate
    networks:
      - temar_net

volumes:
  pg_data_prod:

networks:
  temar_net:
