name: Build, Push & Deploy Web App (Self-Hosted)

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ghcr.io/${{ github.repository_owner}}/temar-web:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up pnpm
        run: npm install -g pnpm

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -f apps/web/Dockerfile.web -t $IMAGE_NAME --target prod .
      - name: Push Docker image to GHCR
        run: |
          docker push $IMAGE_NAME

      - name: Build and push migration image
        run: |
          docker build -f libs/db-client/Dockerfile.migrate -t ghcr.io/${{ github.repository_owner }}/migrate:latest .
          docker push ghcr.io/${{ github.repository_owner }}/migrate:latest

      - name: Create .env for production
        run: |
          echo 'Creating .env file...'
          cat > .env <<EOL
          DATABASE_HOST=${{ secrets.DATABASE_HOST }}
          DATABASE_USER=${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME=${{ secrets.DATABASE_NAME }}
          DATABASE_PORT=${{ secrets.DATABASE_PORT }}

          BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }}
          BETTER_AUTH_URL=${{ secrets.BETTER_AUTH_URL }}

          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          GH_CLIENT_ID=${{ secrets.GH_CLIENT_ID }}
          GH_CLIENT_SECRET=${{ secrets.GH_CLIENT_SECRET }}
          EOL

      - name: Run database migrations
        run: |
          echo 'Running database migrations...'
          docker run --rm --env-file .env --network temar_net ghcr.io/${{ github.repository_owner }}/migrate:latest

      - name: Verify .env exists
        run: |
          if [ -f .env ]; then
            echo ".env file exists."
          else
            echo ".env file does not exist!"
            exit 1
          fi

      - name: Deploy using docker-compose
        run: |
          echo 'Pulling and redeploying containers...'
          docker compose -f docker-compose.prod.yml pull
          docker compose -f docker-compose.prod.yml up -d --remove-orphans

      - name: Remove .env file
        run: |
          echo 'Removing .env file...'
          rm .env
      - name: Clean up dangling images
        run: |
          echo 'Cleaning up dangling images...'
          docker image prune -f
